name: Build Alkad2588WH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        git clone https://github.com/microsoft/Detours.git external/detours
        git clone https://github.com/ocornut/imgui.git external/imgui

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release